apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-ip-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-ip-controller
rules:
  - apiGroups: [""]
    resources: ["services", "services/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-ip-controller
subjects:
  - kind: ServiceAccount
    name: external-ip-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-ip-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: external-ip-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-ip-controller
  template:
    metadata:
      labels:
        app: external-ip-controller
    spec:
      serviceAccountName: external-ip-controller
      containers:
        - name: controller
          image: ghcr.io/tcurdt/kube-external-ip-controller:latest
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
