apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-ip-controller
subjects:
  - kind: ServiceAccount
    name: external-ip-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-ip-controller
  apiGroup: rbac.authorization.k8s.io 