apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-ip-controller
rules:
  - apiGroups: [""]
    resources: ["services", "services/status"]
    verbs: ["get", "list", "watch", "update", "patch"] 